---
title: "Data viz"
author: "Elise Gonzales"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)
library(gapminder)
library(sf)
library(ggpubr)
library(jpeg)
library(ggimage)
```

```{r}

```


```{r}
space_launches <- read_csv(here("data", "space_launches.csv"))

ggplot(data = space_launches,
       aes(x = launch_year)) + 
  geom_histogram(aes(y=..density..), colour="purple2", fill = "orange", linetype = "dashed") +
  geom_density(color = "#000000", fill = "purple", alpha=.2) + geom_vline(aes(xintercept=mean(launch_year), color = launch_year)) + labs(x = "Year of Launch (year)", y = "Numbers") + scale_color_gradientn(colors = c("purple2", "cyan4", "chartreuse", "yellow", "orange")) +  geom_vline(xintercept = c(2020, 2000, 1980, 1960), linetype = "3313", color = "brown", size = 10) 
```

